version: '3.4'

services:
  postgres:
    container_name: userrole-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
       - ./database:/var/lib/postgresql
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: userroles
      POSTGRES_PASSWORD: userroles
      